 #------------------------------------------------------------------------------------------------------------------------------------
#  The Nautilus DevOps team needs to copy data from the jump host to all application 
#  servers in Stratos DC using Ansible.Execute the task with the following details:
#  a. Create an inventory file /home/thor/ansible/inventory on jump_host and add all application servers as managed nodes.
#  b. Create a playbook /home/thor/ansible/playbook.yml on the jump host to copy the /usr/src/itadmin/index.html file 
#  to all application servers, placing it at /opt/itadmin. Note: Validation will run the playbook using the 
#  command ansible-playbook -i inventory playbook.yml. Ensure the playbook functions properly without any extra arguments.
#------------------------------------------------------------------------------------------------------------------------------------- 
 - hosts: appservers
   become: yes
   become_user: root
   tasks:
     - name: copy file from jump host
       copy:
         src: /usr/src/devops/index.html
         dest: /opt/devops